var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                               ",
   "  x                      *        ",
   "  xxx#xxxxxxxxxxxxxxxxxxxx        ",
   "  x                ||||||x        ",
   "  x                      xxx      ",
   "  x                      x        ",
   "  x                      x        ",
   "  x                      x      xx",
   "  x                      x        ",
   "  x                      x        ",
   "  x                      xxx      ",
   "  x                      x        ",
   "  x                      x        ",
   "  x                      x      xx",
   "  x                      x        ",
   "  x                      xxx      ",
   "  x                      x        ",
   "  x                      x        ",
   "oox                      x   @  xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                  "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "x                 |          o x ",
   "x                            o x ",
   "xxxx          *             xxxx ",
   "x            xxxxxxxxxxxxxxxxxxxx ",
   "x            x                   ",
   "x         xx#x                   ",
   "x           =x                   ",
   "x  o         x                   ",
   "xxxx         x                   ",
   "x            x                   ",
   "x         xxxx                   ",
   "x           =x                   ",
   "x            x                   ",
   "xxxx         x                   ",
   "x        o   x                   ",
   "x        xxxxx                   ",
   "x            x                   ",
   "x          = x                   ",
   "xxxx         x                   ",
   "x            x                   ",
   "x            x                   ",
   "x        xxxxx                   ",
   "x            x                   ",
   "xxxxx        x                   ",
   "x         o  x                   ",
   "x            x                   ",
   "x        xxx#x                   ",
   "x           vx                   ",
   "xxxx         x                   ",
   "x            x                   ",
   "x@           x                   ",
   "xxxxxxxxxxxx#x                   ",
   "                                 "],
  ["                                                                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                         xx   xx   !!   yy      x",
   "                                                        x!!x xyyx !yy! y!!y     x",
   "                                                        x!!x xyyx !yy! y!!y     x",
   "                                                         xx   xx   !!   yy      x",
   "  o           o o                         x          o                          x",
   " o*o                                                xxx                         x",
   "!xxx        xxxxxxx      o          o o       x||x                              x",
   "!x   x!!!x              xxxxx      o           xx       xxxx                    x",
   "!x   xxxxx                         xxxx                                         x",
   "xx                                       x                                     xx",
   "x                                                                            oxxx",
   "x                       o                   x                                xxxx",
   "x           x      xxxxxx                                         oo        xxxxx",
   "x                     o                                           xxx            ",
   "x  @              o                                           x                 =",
   "xxxxxxxxxxx!!!#xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxx     xxxxxxx      xxxxxxx!!!!!!",
   "         xx   xx   !!   **    x   x              x   x x     x!!!!!!!x     !!!!!!",
   "        x!!x xyyx !**! *!!*   x!!!x        xx    xyx!!!x     x!!!!!!!x           ",
   "        x!!x xyyx !**! *!!*   x!!!x       x**x   xxx!!!x     x!!!!!!!x           ",
   "         xx   xx   !!   **    xxxxx       x**x   xxxxxxx     xxxxxxxxx           ",
   "                                           xx                                    ",
   "                                                                                 "],
  ["                                                                                                              ",
   "  @                                                                                                           ",
   "         vvv x x   xx   x x vvv x   x   xx   x  x   x  x  x                                                   ",
   "             x x  x  x  x x     x x x   xx   xx x   x  x  x                                                   ",
   "              x   x  x  x x     x x x   xx   x xx                                                             ",
   "              x    xx    x       x x    xx   x  x   x  x  x                                                   ",
   "                                                                                                              ",
   "             x x   xx   x x     x   x   xx   x  x   x  x  x                                                   ",
   "             x x  x  x  x x     x x x   xx   xx x   x  x  x                                                   ",
   "              x   x  x  x x     x x x   xx   x xx                                                             ",
   "              x    xx    x       x x    xx   x  x   x  x  x                                                   ",
   "                                                                                                              ",
   "             x x   xx   x x     x   x   xx   x  x   x  x  x                                                   ",
   "             x x  x  x  x x     x x x   xx   xx x   x  x  x                                                   ",
   "              x   x  x  x x     x x x   xx   x xx                                                             ",
   "              x    xx    x       x x    xx   x  x   x  x  x                                                   ",
   "                                                                                                              ",
   "             x x   xx   x x     x   x   xx   x  x   x  x  x                                                   ",
   "             x x  x  x  x x     x x x   xx   xx x   x  x  x                                                   ",
   "              x   x  x  x x     x x x   xx   x xx                                                             ",
   "              x    xx    x       x x    xx   x  x   x  x  x                                                   ",
   "                                                                                                              ",
   "             x x   xx   x x     x   x   xx   x  x   x  x  x                                                   ",
   "             x x  x  x  x x     x x x   xx   xx x   x  x  x                                                   ",
   "              x   x  x  x x     x x x   xx   x xx                                                             ",
   "              x    xx    x       x x    xx   x  x   x  x  x                                                   ",
   "                                                                                                              ",
   "             x x   xx   x x     x   x   xx   x  x   x  x  x                                                   ",
   "             x x  x  x  x x     x x x   xx   xx x   x  x  x                                                   ",
   "              x   x  x  x x     x x x   xx   x xx                                                             ",
   "              x    xx    x       x x    xx   x  x   x  x  x                                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "   *                                                                                                         o",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
